version: '3'

services:
    ubii-web-frontend:
        build: 
            dockerfile: ubii-web.dockerfile
            context: ./
        ports:
            - 8080:8080
        depends_on:
            - ubii-node-master
        networks:
            - ubii-network
    ubii-node-master:
        build: 
            dockerfile: ubii-master.dockerfile
            context: ./
        ports:
            - 8101:8101
            - 8102:8102
            - 8103:8103
            - 8104:8104
        networks:
            - ubii-network
networks:
    ubii-network:
        
